### ISSUE TITLE
Project Nicolas IHC Checklist

### ISSUE THREAD

**Issue by irinabelaia** [Turku-BioImaging/nicolas-pasquier-crc-manuscript#2]
Samples: 
- 24 FFPE tumor sections that were immunohistochemically stained for three proteins: HER2, HER3 and SORLA
- 48 images (24 for the HER2/SORLA staining, 24 for the HER2/HER3 staining)
- the cancer parts keep their epithelial features and present two polarity phenotypes (apical-in and apical-out)
- Mix 1:
  - HER2 = Cy3 / Ch2
  - SORLA = AF647 / Ch3
- Mix 2:
  - HER2 = Cy3 / Ch2
  - HER3 = AF647 / Ch3

Requested analysis:
- Measure the intensity of each signal (SORLA, HER2, HER3) in the whole cancer region and in the epithelial cancer region (apical pole and basal pole)

Tasks:
- [x] Improve ROIs/masks for apical-in by drawing manual ROIs
- [x] Recalculate the intensity analysis in all requested regions with the updated ROIs 
- [x] Correlation analysis of intensity HER2 vs HER3 and HER2 vs SORLA within on patient samples for 1) whole region, (apical-in and apical-out), and for 2) basal and apical pole zones separately. Plot the correlations for each individual ROI and for the average per patient
- [x] To compare the intensity between zones, normalize the intensity value to ROI areas
- [x] In addition to the normalization by ROI area, perform the normalization by cell number within the ROI (segmentation and counting the cell nuclei within ROIs)? // Nicolas asked 29.04.2024 
- [x] Investigate mean intensities over the entire data, comparing Zeiss- and BioFormats-derived images.

Inside note: _In vitro_ there is a correlation between HER2 and HER3 (for apical-in) and the overall intensity lower in apical-out in comparison to apical-in
